In [28]:
import pandas as pd
import numpy as np
import matplotlib as plt
%matplotlib inline

In [36]:
df = pd.read_csv('AdventureWorks2019.csv', sep=';', header=0)

In [38]:
#dictionaty = {0: 'ProductID', 1: 'ListPrice', 2: 'StandardCost',3:'Color', 4:'Size',5:'SizeUMC', 6:'Weight', 7:'WeightUMC',8:'Style', 9:'class',10:'SubCatName',11:'CatName', 12:'UnitPrice', 13:'UnitPriceDisc', 14:'OrderQty', 15:'TotalDue', 16:'SubTotal',17:'TerritoryID', 18:'OnlineOrderFlag',19:'Status', 20:'SellStart', 21:'SellEnd' }

In [40]:
#df.rename(columns=dictionaty, inplace=True)

In [41]:
df

,ProductID,ListPrice,StandardCost,Color,Size,SizeUnitMeasureCode,Weight,WeightUnitMeasureCode,Style,class,...,UnitPrice,UnitPriceDiscount,OrderQty,TotalDue,SubTotal,TerritoryID,OnlineOrderFlag,Status,SellStartDate,SellEndDate
0,776,"3374,99","1898,0944",Black,42,CM,20.77,LB,U,H,...,"2024,994","0,00",1,"23153,2339","20565,6206",5,0,5,2011-05-31 00:00:00.000,2012-05-29 00:00:00.000
1,777,"3374,99","1898,0944",Black,44,CM,21.13,LB,U,H,...,"2024,994","0,00",3,"23153,2339","20565,6206",5,0,5,2011-05-31 00:00:00.000,2012-05-29 00:00:00.000
2,778,"3374,99","1898,0944",Black,48,CM,21.42,LB,U,H,...,"2024,994","0,00",1,"23153,2339","20565,6206",5,0,5,2011-05-31 00:00:00.000,2012-05-29 00:00:00.000
3,771,"3399,99","1912,1544",Silver,38,CM,20.35,LB,U,H,...,"2039,994","0,00",1,"23153,2339","20565,6206",5,0,5,2011-05-31 00:00:00.000,2012-05-29 00:00:00.000
4,772,"3399,99","1912,1544",Silver,42,CM,20.77,LB,U,H,...,"2039,994","0,00",1,"23153,2339","20565,6206",5,0,5,2011-05-31 00:00:00.000,2012-05-29 00:00:00.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121312,878,"21,98","8,2205",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"21,98","0,00",1,"34,2219","30,97",6,1,5,2013-05-30 00:00:00.000,NaN
121313,712,"8,99","6,9223",Multi,NaN,NaN,NaN,NaN,U,NaN,...,"8,99","0,00",1,"34,2219","30,97",6,1,5,2011-05-31 00:00:00.000,NaN
121314,878,"21,98","8,2205",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"21,98","0,00",1,"209,9169","189,97",6,1,5,2013-05-30 00:00:00.000,NaN
121315,879,"159,00","59,466",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"159,00","0,00",1,"209,9169","189,97",6,1,5,2013-05-30 00:00:00.000,NaN
121316,712,"8,99","6,9223",Multi,NaN,NaN,NaN,NaN,U,NaN,...,"8,99","0,00",1,"209,9169","189,97",6,1,5,2011-05-31 00:00:00.000,NaN

In [42]:
df.to_csv('AdventureWorks2019.csv')

In [45]:
df2 = pd.read_csv('AdventureWorksAllProducts.csv', sep=';', header=0)

In [16]:
#df2.rename(columns=dictionaty, inplace=True)

In [24]:
df2.to_csv('AdventureWorksAllProducts.csv')

In [47]:
pd.read_csv('UnsalledProducts.csv', sep=';', header=0)

,Name,ProductID,ListPrice,StandardCost,Color,Size,SizeUnitMeasureCode,Weight,WeightUnitMeasureCode,Style,class,SubCatName,CatName,SellStartDate,SellEndDate
0,HL Touring Seat Assembly,522,"196,92","145,87",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00.000,NaN
1,ML Touring Seat Assembly,521,"147,14","108,99",NaN,NaN,NaN,NaN,NaN,NaN,M,NaN,NaN,2008-04-30 00:00:00.000,NaN
2,LL Touring Seat Assembly,520,"133,34","98,77",NaN,NaN,NaN,NaN,NaN,NaN,L,NaN,NaN,2008-04-30 00:00:00.000,NaN
3,HL Road Seat Assembly,519,"196,92","145,87",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00.000,NaN
4,ML Road Seat Assembly,518,"147,14","108,99",NaN,NaN,NaN,NaN,NaN,NaN,M,NaN,NaN,2008-04-30 00:00:00.000,NaN
5,LL Road Seat Assembly,517,"133,34","98,77",NaN,NaN,NaN,NaN,NaN,NaN,L,NaN,NaN,2008-04-30 00:00:00.000,NaN
6,HL Mountain Seat Assembly,516,"196,92","145,87",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00.000,NaN
7,ML Mountain Seat Assembly,515,"147,14","108,99",NaN,NaN,NaN,NaN,NaN,NaN,M,NaN,NaN,2008-04-30 00:00:00.000,NaN
8,LL Mountain Seat Assembly,514,"133,34","98,77",NaN,NaN,NaN,NaN,NaN,NaN,L,NaN,NaN,2008-04-30 00:00:00.000,NaN
9,ML Road Handlebars,812,"61,92","27,4925",NaN,NaN,NaN,NaN,NaN,NaN,M,Handlebars,Components,2012-05-30 00:00:00.000,NaN
10,ML Bottom Bracket,995,"101,24","44,9506",NaN,NaN,NaN,168.00,G,NaN,M,Bottom Brackets,Components,2013-05-30 00:00:00.000,NaN
11,ML Fork,803,"175,49","77,9176",NaN,NaN,NaN,NaN,NaN,NaN,M,Forks,Components,2012-05-30 00:00:00.000,2013-05-29 00:00:00.000
12,"HL Mountain Frame - Black, 46",746,"1349,60","739,041",Black,46,CM,2.84,LB,U,H,Mountain Frames,Components,2011-05-31 00:00:00.000,NaN
13,"HL Mountain Frame - Silver, 44",740,"1364,50","706,811",Silver,44,CM,2.76,LB,U,H,Mountain Frames,Components,2011-05-31 00:00:00.000,2012-05-29 00:00:00.000
14,"LL Road Frame - Black, 48",737,"337,22","204,6251",Black,48,CM,2.36,LB,U,L,Road Frames,Components,2011-05-31 00:00:00.000,NaN
15,"ML Road Frame - Red, 60",735,"594,83","352,1394",Red,60,CM,2.38,LB,U,M,Road Frames,Components,2011-05-31 00:00:00.000,2012-05-29 00:00:00.000
16,"ML Road Frame - Red, 58",734,"594,83","352,1394",Red,58,CM,2.36,LB,U,M,Road Frames,Components,2011-05-31 00:00:00.000,2012-05-29 00:00:00.000
17,"ML Road Frame - Red, 44",731,"594,83","352,1394",Red,44,CM,2.22,LB,U,M,Road Frames,Components,2011-05-31 00:00:00.000,2012-05-29 00:00:00.000
18,"LL Road Frame - Red, 58",728,"337,22","187,1571",Red,58,CM,2.46,LB,U,L,Road Frames,Components,2011-05-31 00:00:00.000,2013-05-29 00:00:00.000
19,"LL Road Frame - Black, 62",724,"337,22","204,6251",Black,62,CM,2.50,LB,U,L,Road Frames,Components,2011-05-31 00:00:00.000,NaN
20,"HL Road Frame - Red, 56",721,"1431,50","868,6342",Red,56,CM,2.24,LB,U,H,Road Frames,Components,2011-05-31 00:00:00.000,NaN
21,"HL Road Frame - Red, 52",720,"1431,50","868,6342",Red,52,CM,2.20,LB,U,H,Road Frames,Components,2011-05-31 00:00:00.000,NaN
22,"HL Road Frame - Red, 58",706,"1431,50","1059,31",Red,58,CM,2.24,LB,U,H,Road Frames,Components,2008-04-30 00:00:00.000,NaN
23,"HL Road Frame - Black, 58",680,"1431,50","1059,31",Black,58,CM,2.24,LB,U,H,Road Frames,Components,2008-04-30 00:00:00.000,NaN
24,"HL Road Frame - Black, 52",840,"1431,50","868,6342",Black,52,CM,2.20,LB,U,H,Road Frames,Components,2012-05-30 00:00:00.000,NaN
25,"HL Road Frame - Black, 62",837,"1431,50","868,6342",Black,62,CM,2.30,LB,U,H,Road Frames,Components,2012-05-30 00:00:00.000,NaN
26,"ML Road Frame-W - Yellow, 42",834,"594,83","360,9428",Yellow,42,CM,2.26,LB,W,M,Road Frames,Components,2012-05-30 00:00:00.000,NaN
27,ML Road Seat/Saddle,912,"39,14","17,3782",NaN,NaN,NaN,NaN,NaN,NaN,M,Saddles,Components,2013-05-30 00:00:00.000,NaN
28,"LL Touring Frame - Yellow, 54",901,"333,42","199,8519",Yellow,54,CM,3.14,LB,U,L,Touring Frames,Components,2013-05-30 00:00:00.000,NaN
29,Touring Rear Wheel,829,"245,01","108,7844",Black,NaN,NaN,NaN,NaN,NaN,NaN,Wheels,Components,2012-05-30 00:00:00.000,2013-05-29 00:00:00.000
30,Touring Front Wheel,821,"218,01","96,7964",Black,NaN,NaN,NaN,NaN,NaN,NaN,Wheels,Components,2012-05-30 00:00:00.000,2013-05-29 00:00:00.000
31,LL Road Front Wheel,818,"85,565","37,9909",Black,NaN,NaN,900.00,G,NaN,L,Wheels,Components,2012-05-30 00:00:00.000,2013-05-29 00:00:00.000
32,"Men's Sports Shorts, XL",851,"59,99","24,7459",Black,XL,NaN,NaN,NaN,M,NaN,Shorts,Clothing,2012-05-30 00:00:00.000,2013-05-29 00:00:00.000
33,Headlights - Weatherproof,848,"44,99","18,5584",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lights,Accessories,2012-05-30 00:00:00.000,2013-05-29 00:00:00.000
34,Headlights - Dual-Beam,847,"34,99","14,4334",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lights,Accessories,2012-05-30 00:00:00.000,2013-05-29 00:00:00.000
35,Taillights - Battery-Powered,846,"13,99","5,7709",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lights,Accessories,2012-05-30 00:00:00.000,2013-05-29 00:00:00.000
36,"Touring-Panniers, Large",842,"125,00","51,5625",Grey,NaN,NaN,NaN,NaN,NaN,NaN,Panniers,Accessories,2012-05-30 00:00:00.000,2013-05-29 00:00:00.000
37,Mountain Pump,845,"24,99","10,3084",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pumps,Accessories,2012-05-30 00:00:00.000,2013-05-29 00:00:00.000

In [20]:
dictionaty = {0: 'ProductID', 1: 'ListPrice', 2: 'StandardCost',3:'Color', 4:'Size',5:'SizeUMC', 6:'Weight', 7:'WeightUMC',8:'Style', 9:'class',10:'SubCatName',11:'CatName'}

In [21]:
df3.rename(columns=dictionaty, inplace=True)

In [27]:
df3.to_csv('UnsalledProducts.csv')