In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv('../GroupedData/2012-2013_Gr_Avlb_2013_sub_color_size_class.csv', sep=";")

In [6]:
MBikes = df[df['SubName'] == 'Mountain Bikes']

In [7]:
MBikes

,SubName,Class,Color,Size,totalSellAmt,totalCosts,totalQuantity,GP
0,Mountain Bikes,H,Black,38.0,"1809179,926","1706450,5119",1363,"102729,4141"
1,Mountain Bikes,H,Black,42.0,"1739911,1873","1621315,7835",1295,"118595,4038"
2,Mountain Bikes,H,Black,46.0,"1350095,8752","1209413,9358",966,"140681,9394"
3,Mountain Bikes,H,Black,NaN,"4899186,9885","4537180,2312",3624,"362006,7573"
4,Mountain Bikes,H,Silver,38.0,"1530625,0072","1414962,601",1118,"115662,4062"
5,Mountain Bikes,H,Silver,42.0,"1519788,1685","1409900,123",1114,"109888,0455"
6,Mountain Bikes,H,Silver,46.0,"1528008,3894","1407368,884",1112,"120639,5054"
7,Mountain Bikes,H,Silver,NaN,"4578421,5651","4232231,608",3344,"346189,9571"
8,Mountain Bikes,H,NaN,NaN,"9477608,5536","8769411,8392",6968,"708196,7144"
9,Mountain Bikes,NaN,NaN,NaN,"9477608,5536","8769411,8392",6968,"708196,7144"

In [8]:
df

,SubName,Class,Color,Size,totalSellAmt,totalCosts,totalQuantity,GP
0,Mountain Bikes,H,Black,38.0,"1809179,926","1706450,5119",1363,"102729,4141"
1,Mountain Bikes,H,Black,42.0,"1739911,1873","1621315,7835",1295,"118595,4038"
2,Mountain Bikes,H,Black,46.0,"1350095,8752","1209413,9358",966,"140681,9394"
3,Mountain Bikes,H,Black,NaN,"4899186,9885","4537180,2312",3624,"362006,7573"
4,Mountain Bikes,H,Silver,38.0,"1530625,0072","1414962,601",1118,"115662,4062"
5,Mountain Bikes,H,Silver,42.0,"1519788,1685","1409900,123",1114,"109888,0455"
6,Mountain Bikes,H,Silver,46.0,"1528008,3894","1407368,884",1112,"120639,5054"
7,Mountain Bikes,H,Silver,NaN,"4578421,5651","4232231,608",3344,"346189,9571"
8,Mountain Bikes,H,NaN,NaN,"9477608,5536","8769411,8392",6968,"708196,7144"
9,Mountain Bikes,NaN,NaN,NaN,"9477608,5536","8769411,8392",6968,"708196,7144"
10,Road Bikes,H,Black,44.0,"1254395,8239","1362134,3604",876,"-107738,5365"
11,Road Bikes,H,Black,48.0,"1149797,7522","1220634,1015",785,"-70836,3493"
12,Road Bikes,H,Black,52.0,"1037551,125","1054254,6762",678,"-16703,5512"
13,Road Bikes,H,Black,58.0,"763110,5625","757259,6273",487,"5850,9352"
14,Road Bikes,H,Black,NaN,"4204855,2636","4394282,7654",2826,"-189427,5018"
15,Road Bikes,H,Red,58.0,"822012,75","799243,2206",514,"22769,5294"
16,Road Bikes,H,Red,NaN,"822012,75","799243,2206",514,"22769,5294"
17,Road Bikes,H,NaN,NaN,"5026868,0136","5193525,986",3340,"-166657,9724"
18,Road Bikes,M,Yellow,38.0,"535907,5576","603265,5108",846,"-67357,9532"
19,Road Bikes,M,Yellow,40.0,"466203,875","521974,4136",732,"-55770,5386"
20,Road Bikes,M,Yellow,42.0,"373363,275","410733,9648",576,"-37370,6898"
21,Road Bikes,M,Yellow,44.0,"283523,9875","300206,5958",421,"-16682,6083"
22,Road Bikes,M,Yellow,48.0,"536593,8582","606117,83",850,"-69523,9718"
23,Road Bikes,M,Yellow,NaN,"2195592,5533","2442298,315",3425,"-246705,7617"
24,Road Bikes,M,NaN,NaN,"2195592,5533","2442298,315",3425,"-246705,7617"
25,Road Bikes,NaN,NaN,NaN,"7222460,5669","7635824,301",6765,"-413363,7341"